dev/Login/urls.py
from django.conf.urls import url
from . import views

app_name='Login'
urlpatterns = [
	#url(r'^$', views.index, name='index'),
	url(r'^signup/$',views.signup,name='signup'),
	url(r'^signin/$',views.signin,name='signin'),
	url(r'^signout/$',views.signout,name='signout'),
]

dev/dev/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Login/', include('Login.urls')),
   	url(r'^main/', include('main.urls'))
]

dev/main/urls.py
from django.conf.urls import url
from . import views

app_name='main'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^add/$',views.add, name='add'),#done
   	url(r'^disp/$',views.disp, name='disp'),
   	url(r'^wrong/$',views.wrong, name='wrong'),	
]

dev/Login/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
#from Game.models import GroupDetails

# Create your models here.

class UserProfile(models.Model):
	types = (('Mess Worker','Mess Worker'),('Student','Student'))
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	typid = models.CharField(max_length = 30,choices = types,default='Student')
	extras = models.IntegerField(max_length = 5,default = 0)
	regno = models.IntegerField(max_length = 6)


	def __str__(self):
		return self.user.first_name

dev/main/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone


class Purchase(models.Model):

	regno = models.IntegerField(max_length = 6)
	item = models.CharField(max_length = 30)
	quantity = models.IntegerField(max_length = 3)
	price = models.IntegerField(max_length = 4)
	date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		# t = (item + char(quantity) + char(regno))
		return self.item

class Items(models.Model):
	name = models.CharField(max_length = 30)
	price = models.IntegerField(max_length = 10)

	def __str__(self):
		return self.name


# Create your models here.

dev/Login/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User,UserManager,AbstractBaseUser
from django.contrib.auth import authenticate,login,logout
from .models import UserProfile

# Create your views here.
def index(request):
	return render(request,'Login/signin.html',None)

def signin(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		print(user)
		if user is None:
			return render(request,'Login/signin.html',{'error':'Invalid username or password'})
		else:
			login(request,user)
		return redirect('/main')#render the dashboard page
	else:
		return render(request,'Login/signin.html',None)

def signup(request):
# print "hi there"
# if request.user.is_authenticated() == True and request.user.is_active == True:
# 	return render(request,'Login/dashboard.html',None)
	if request.method == 'POST':
		firstName = request.POST['first_name']
		password = request.POST['password']
		password2 = request.POST['re_password']
		username = request.POST['username']
		lastName = request.POST['last_name']
		if password2 != password:
			return render(request,'Login/signup.html',{'error':'Password doesn\'t match'})
		emailAddr = request.POST['email']
		contact = request.POST.get('contact')
		address = request.POST['address']
		regno = request.POST.get('regno')
		typid = request.POST.get('typid')
		try:
			u = User._default_manager.get(username__iexact=username) #fix for case sensitive username
			return render(request,'Login/signup.html',{'error':'username already already exists!'})
		except User.DoesNotExist:
			user = User.objects.create_user(username=username,email=emailAddr,first_name=firstName,last_name=lastName)
			user.set_password(password)
			user.is_active = True
			# print "hi there"
			user.save()
			profileobject = UserProfile(user=user,address=address,mbno=contact,regno=regno,typid=typid)
			profileobject.save()
			user.backend = 'django.contrib.auth.backends.ModelBackend' #user backend error fix
			authenticate(username=username,password=password)
			login(request,user)
			return redirect('/main')
	else:
		return render(request,'Login/signup.html',None) 

def signout(request):
	logout(request)
	return render(request,'Login/signin.html',None)
def lksignup(request):
	return render(request,'Login/signup.html',None)

dev/main/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User,UserManager,AbstractBaseUser
from django.contrib.auth import authenticate,login,logout
from Login.models import UserProfile
from .models import Purchase,Items

def index(request):
	user = request.user
	u = UserProfile.objects.filter(user = user)
	if len(u) > 0:
		if (u[0].typid=="Student"): 
			return redirect('/main/disp')
		elif(u[0].typid=="Mess Worker"):
			item = Items.objects.all
			return render(request,'main/test1.html',{'item':item})
	else:
		raise Http404

def add(request):
	if  request.method == 'POST':
		regno = request.POST['regno']
		item = request.POST['item']
		quant = int(request.POST['quant'])
		q=Items.objects.filter(name=item)
		perprice=int(q[0].price)
		price1 = (quant * perprice)
		m=UserProfile.objects.filter(regno = regno)
		t=m[0].extras
		price2=t+price1
		pur = Purchase(regno=regno,item=item,quantity=quant,price=price1)
		pur.save()
		use = UserProfile.objects.filter(regno = regno).update(extras =price2)
		return render(request,'main/show.html',{'item':item,'quant':quant,'pur':pur})
	else:
		raise Http404


def disp(request):

	u=request.user
	us = UserProfile.objects.filter(user = u)
	ext = us[0].extras
	regno = us[0].regno
	rec = Purchase.objects.filter( regno = regno)
	return render(request,'main/list.html',{'rec':rec,'ext':ext})


def wrong(request):

	gi = request.GET.get('gi')
	m=Purchase.objects.filter(id = gi)
	r=m[0].regno
	p=m[0].price
	u=UserProfile.objects.filter(regno = r)
	p1=u[0].extras
	p2=(p1-p)
	use = UserProfile.objects.filter(regno = r).update(extras=p2)
	Purchase.objects.filter(id = gi).delete()
	return render(request,'main/add.html')



# Create your views here.

dev/Login/templates/Login/signin.html
<head>
  {% load staticfiles %}
  {% load static %}
  <!-- <script type="text/javascript" src="{% static 'css/materialize/js/jquery-1.11.1.min.js' %}"></script>
    <script type="text/javascript" src = "{% static 'css/materialize/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>


  <link rel="stylesheet" type="text/css" href="{% static 'css/materialize/css/materialize.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> 
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" /> -->
  <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
  <script type="text/javascript" src = "{% static 'css/materialize/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/materialize/css/materialize.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> 
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/materialize/css/style.css' %}" />
</head>
{% load static %}
<body>
  <nav class="navbar navbar-fixed-top #F5F3F3" role="navigation"> 
    <div class="container">
    </div>
  </nav>
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center orange-text text-lighten-2">Game On</h1>
        <div class="row center" >
          <form action="{% url 'Login:signin' %}" method="post" class="center">
            {% csrf_token %}
            <div class="row">
              <div class="input-field col s6">
                <input name="username" id="username" type="text" placeholder = "Username" style="color: #000000">
                <!-- <label for="Username">User Name</label> -->
              </div>    
              <div class="row">
                <div class="input-field col s6">
                  <input name="password" id="password" type="password" placeholder="Password" style="color: #000000">
                  <!-- <label for="password">Password</label> -->
                </div>
              </div>
            </div>
            <div class="row center">
              <input type="submit" class=" btn green darken-4 thin-letters-3" value = "Sign in">
              <br><br><br><br><br><br><br><br><br>
              <a href="/Login/lksignup">Sign Up</a>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- <div class="parallax"><img src="{% static 'images/n1.jpg' %}" alt="Unsplashed background img 1"> -->
    <!-- </div> -->
  </div>


  
  <footer class="page-footer #F5F3F3">
   <div class="footer-copyright">
    <div class="container">
      <div class="right align">
        Designed by ANIB
      </div>
    </div>
  </div></footer>

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

</body>
</html>

dev/Login/templates/Login/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Extras</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 400 15px Lato, sans-serif;
      line-height: 1.8;
      color: #818181;
  }
  h2 {
      font-size: 24px;
      text-transform: uppercase;
      color: #303030;
      font-weight: 600;
      margin-bottom: 30px;
  }
  h4 {
      font-size: 19px;
      line-height: 1.375em;
      color: #303030;
      font-weight: 400;
      margin-bottom: 30px;
  }  
  .jumbotron {
      background-color: #f4511e;
      color: #fff;
      padding: 100px 25px;
      font-family: Montserrat, sans-serif;
  }
  .container-fluid {
      padding: 60px 50px;
  }
  .bg-grey {
      background-color: #f6f6f6;
  }
  .logo-small {
      color: #f4511e;
      font-size: 50px;
  }
  .logo {
      color: #f4511e;
      font-size: 200px;
  }
  .thumbnail {
      padding: 0 0 15px 0;
      border: none;
      border-radius: 0;
  }
  .thumbnail img {
      width: 100%;
      height: 100%;
      margin-bottom: 10px;
  }
  .carousel-control.right, .carousel-control.left {
      background-image: none;
      color: #f4511e;
  }
  .carousel-indicators li {
      border-color: #f4511e;
  }
  .carousel-indicators li.active {
      background-color: #f4511e;
  }
  .item h4 {
      font-size: 19px;
      line-height: 1.375em;
      font-weight: 400;
      font-style: italic;
      margin: 70px 0;
  }
  .item span {
      font-style: normal;
  }
  .panel {
      border: 1px solid #f4511e; 
      border-radius:0 !important;
      transition: box-shadow 0.5s;
  }
  .panel:hover {
      box-shadow: 5px 0px 40px rgba(0,0,0, .2);
  }
  .panel-footer .btn:hover {
      border: 1px solid #f4511e;
      background-color: #fff !important;
      color: #f4511e;
  }
  .panel-heading {
      color: #fff !important;
      background-color: #f4511e !important;
      padding: 25px;
      border-bottom: 1px solid transparent;
      border-top-left-radius: 0px;
      border-top-right-radius: 0px;
      border-bottom-left-radius: 0px;
      border-bottom-right-radius: 0px;
  }
  .panel-footer {
      background-color: white !important;
  }
  .panel-footer h3 {
      font-size: 32px;
  }
  .panel-footer h4 {
      color: #aaa;
      font-size: 14px;
  }
  .panel-footer .btn {
      margin: 15px 0;
      background-color: #f4511e;
      color: #fff;
  }
  .navbar {
      margin-bottom: 0;
      background-color: #f4511e;
      z-index: 9999;
      border: 0;
      font-size: 12px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #f4511e !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  footer .glyphicon {
      font-size: 20px;
      margin-bottom: 20px;
      color: #f4511e;
  }
  .slideanim {visibility:hidden;}
  .slide {
      animation-name: slide;
      -webkit-animation-name: slide;
      animation-duration: 1s;
      -webkit-animation-duration: 1s;
      visibility: visible;
  }
  @keyframes slide {
    0% {
      opacity: 0;
      transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      transform: translateY(0%);
    }
  }
  @-webkit-keyframes slide {
    0% {
      opacity: 0;
      -webkit-transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      -webkit-transform: translateY(0%);
    }
  }
  @media screen and (max-width: 768px) {
    .col-sm-4 {
      text-align: center;
      margin: 25px 0;
    }
    .btn-lg {
        width: 100%;
        margin-bottom: 35px;
    }
  }
  @media screen and (max-width: 480px) {
    .logo {
        font-size: 150px;
    }
  }
  </style>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
    <br><br><br>   
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>  

      </button>
    </div>
      </div>
        </div>
        </div>
        </nav>
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center orange-text text-lighten-2" style="margin-left:450px; ">OMAHA MESS</h1>
        <div class="row center" >
      
<form action="{% url 'Login:signup' %}" method="POST">
{% csrf_token %}
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="first_name" class="col-form-label"></label>
					<input name="first_name" class="form-control" type="text" placeholder= "First Name">
				</div>
			</div>
		<div class="form-group col-md-6">
			<label for="last_name" class="col-form-label"></label>
			<input type="text" class="form-control" name="last_name" placeholder="Last Name">
		</div>
	<div class="form-group">
		<label for="username" class="col-form-label"></label>
		<input type="text" class="form-control" name="username" placeholder="Username">
	</div>
	<div class="form-group">
		<label for="password" class="col-form-label"></label>
		<input type="password" class="form-control" name="password" placeholder="Password">
	</div>
	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="re_password" class="col-form-label"></label>
			<input type="password" class="form-control" name="re_password" placeholder="Re-Type Password">
		</div>
		<div class="form-group col-md-4">
			<label for="email" class="col-form-label"></label>
			<input type="text" name="email" class="form-control" placeholder="E-Mail">
		</div>
		<div class="form-group col-md-2">
			<label for="regno" class="col-form-label"></label>
			<input type="text" class="form-control" name="regno" placeholder="Reg No">
		</div>
	</div>
	</div>
		<div class="form-group col-md-3">
		</div>
		<div class="form-group col-md-6">
		<select class="form-control" name="typid">
			<option value="">Choose Type</option>
			<option value="Mess Worker">Mess Worker</option>
			<option value="Student">Student</option>
		</select>
		</div>
	</div>
	<div>
	 <div class="form-group col-md-6">
		</div>
		<div class="form-group col-md-1">
	<button type="submit" class="btn btn-primary btn-lg" style="margin-left: -50px;">Sign in</button>
	</div>
	</div>
</form>
</div></div></div></body></html>

				

dev/main/templates/main/test1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Extras</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 400 15px Lato, sans-serif;
      line-height: 1.8;
      color: #818181;
  }
  h2 {
      font-size: 24px;
      text-transform: uppercase;
      color: #303030;
      font-weight: 600;
      margin-bottom: 30px;
  }
  h4 {
      font-size: 19px;
      line-height: 1.375em;
      color: #303030;
      font-weight: 400;
      margin-bottom: 30px;
  }  
  .jumbotron {
      background-color: #f4511e;
      color: #fff;
      padding: 100px 25px;
      font-family: Montserrat, sans-serif;
  }
  .container-fluid {
      padding: 60px 50px;
  }
  .bg-grey {
      background-color: #f6f6f6;
  }
  .logo-small {
      color: #f4511e;
      font-size: 50px;
  }
  .logo {
      color: #f4511e;
      font-size: 200px;
  }
  .thumbnail {
      padding: 0 0 15px 0;
      border: none;
      border-radius: 0;
  }
  .thumbnail img {
      width: 100%;
      height: 100%;
      margin-bottom: 10px;
  }
  .carousel-control.right, .carousel-control.left {
      background-image: none;
      color: #f4511e;
  }
  .carousel-indicators li {
      border-color: #f4511e;
  }
  .carousel-indicators li.active {
      background-color: #f4511e;
  }
  .item h4 {
      font-size: 19px;
      line-height: 1.375em;
      font-weight: 400;
      font-style: italic;
      margin: 70px 0;
  }
  .item span {
      font-style: normal;
  }
  .panel {
      border: 1px solid #f4511e; 
      border-radius:0 !important;
      transition: box-shadow 0.5s;
  }
  .panel:hover {
      box-shadow: 5px 0px 40px rgba(0,0,0, .2);
  }
  .panel-footer .btn:hover {
      border: 1px solid #f4511e;
      background-color: #fff !important;
      color: #f4511e;
  }
  .panel-heading {
      color: #fff !important;
      background-color: #f4511e !important;
      padding: 25px;
      border-bottom: 1px solid transparent;
      border-top-left-radius: 0px;
      border-top-right-radius: 0px;
      border-bottom-left-radius: 0px;
      border-bottom-right-radius: 0px;
  }
  .panel-footer {
      background-color: white !important;
  }
  .panel-footer h3 {
      font-size: 32px;
  }
  .panel-footer h4 {
      color: #aaa;
      font-size: 14px;
  }
  .panel-footer .btn {
      margin: 15px 0;
      background-color: #f4511e;
      color: #fff;
  }
  .navbar {
      margin-bottom: 0;
      background-color: #f4511e;
      z-index: 9999;
      border: 0;
      font-size: 12px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #f4511e !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  footer .glyphicon {
      font-size: 20px;
      margin-bottom: 20px;
      color: #f4511e;
  }
  .slideanim {visibility:hidden;}
  .slide {
      animation-name: slide;
      -webkit-animation-name: slide;
      animation-duration: 1s;
      -webkit-animation-duration: 1s;
      visibility: visible;
  }
  @keyframes slide {
    0% {
      opacity: 0;
      transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      transform: translateY(0%);
    }
  }
  @-webkit-keyframes slide {
    0% {
      opacity: 0;
      -webkit-transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      -webkit-transform: translateY(0%);
    }
  }
  @media screen and (max-width: 768px) {
    .col-sm-4 {
      text-align: center;
      margin: 25px 0;
    }
    .btn-lg {
        width: 100%;
        margin-bottom: 35px;
    }
  }
  @media screen and (max-width: 480px) {
    .logo {
        font-size: 150px;
    }
  }
  </style>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#myPage">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href = "/main">Home</a></li>
        <li><a href = "/Login/signout">Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron text-center">
  <h1>OMAHA</h1> 
  <p>We serve you the best facilities</p>
 </div> 
 <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
  <form action="{% url 'main:add' %}" method="post" class="col s12">
      {% csrf_token %}
      <div class="form-group col-md-6">
        <label for="regno" class="col-form-label"></label>
          <input name="regno" class="form-control" type="text" placeholder= "Reg No" style="width:200px;margin-left: 20px">
        </div>
      <<!-- div class="form-group col-md-4">
        <input name="regno" type="text" placeholder= "regno" style="    margin-left: 88px;
    height: 46px;
    width: 139px;
    margin-top: 9px" >
      </div> -->
      <div class="form-group col-md-4">
        <select name="item" style="    margin-left: -90px;
    height: 37px;
    width: 163px;
    margin-top: 29px;">
          {% for i in item %}
          <option value={{i.name}}>{{i.name}}</option>
          {% endfor %}
        </select>  
      </div>
       <div class="form-group col-md-6">
        <label for="quant" class="col-form-label"></label>
          <input name="quant" class="form-control" type="text" placeholder= "Quantity" style="width: 200px;
    margin-left: 912px;
    margin-top: -77px;
">
        </div>
      <button type="submit" class="btn btn-primary btn-lg" style=" margin-left: 529px; margin-top: 31px;"> Confirm </button>
    </form>  
</body>
</html>